name: retrofit_generator
description: retrofit generator is an dio client generator using source_gen and inspired by Chopper and Retrofit.
version: 1.4.1+1
publish_to: none

#homepage: https://mings.in/retrofit.dart/
#repository: https://github.com/trevorwang/retrofit.dart/

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  dio: ^4.0.0-beta6
  source_gen: ^1.0.2

  built_collection: ^5.0.0
  code_builder: ^3.2.0
  tuple: ^1.0.2
  analyzer: any
  dart_style: ^2.0.1
  build: ^2.0.0

dev_dependencies:
  retrofit:
    path: ../annotation
  test:
  source_gen_test: any
  resource:
